# Generated by Django 4.2.4 on 2023-09-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
