# Generated by Django 4.2.4 on 2023-09-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conduta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondutaDescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='conduta',
            name='descricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condutadescricao'),
        ),
    ]
