# Generated by Django 4.2.4 on 2023-09-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_procedimento_producao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='cateter',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='hdfc',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='hemodialise',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='parecer_visita',
        ),
        migrations.AlterField(
            model_name='producao',
            name='criado_em',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='producao',
            name='procedimento',
        ),
        migrations.AddField(
            model_name='producao',
            name='procedimento',
            field=models.ManyToManyField(to='core.procedimento'),
        ),
    ]
