# Generated by Django 4.2.4 on 2023-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_producao_procedimento_producao_hdfc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='valor_cateter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='valor_hdfc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='valor_hemodialise',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='valor_parecer',
            field=models.FloatField(default=0),
        ),
    ]
