# Generated by Django 4.2.4 on 2023-09-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_producao_valor_cateter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paciente'),
        ),
    ]
