# Generated by Django 4.2 on 2025-09-04 02:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_producao_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'ordering': ['-data', '-id']},
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='valor',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tipo',
            field=models.CharField(choices=[('bool', 'Booleano (0/1)'), ('int', 'Inteiro (quantidade)')], default='bool', max_length=8),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='producoes', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='total_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producao',
            unique_together={('paciente', 'data')},
        ),
        migrations.CreateModel(
            name='ItemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.procedimento')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.producao')),
            ],
        ),
        migrations.RemoveField(
            model_name='producao',
            name='cateter',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='hdfc',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='hemodialise',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='parecer_visita',
        ),
        migrations.CreateModel(
            name='ProcedimentoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.convenio')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procedimento')),
            ],
            options={
                'unique_together': {('procedimento', 'hospital', 'convenio', 'vigencia_inicio')},
            },
        ),
        migrations.AddIndex(
            model_name='itemproducao',
            index=models.Index(fields=['producao', 'procedimento'], name='core_itempr_produca_44b3d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemproducao',
            unique_together={('producao', 'procedimento')},
        ),
    ]
